/// <reference lib="es2020" />
/// <reference lib="dom" />
/// <reference lib="webworker" />

import { precacheAndRoute } from "workbox-precaching";
import { registerRoute, NavigationRoute } from "workbox-routing";
import { CacheFirst } from "workbox-strategies";
import { CacheableResponsePlugin } from "workbox-cacheable-response";
import { ExpirationPlugin } from "workbox-expiration";

// Precache all assets generated by the build process
declare const self: ServiceWorkerGlobalScope;

precacheAndRoute(self.__WB_MANIFEST || []);

// Cache images
registerRoute(
  ({ request }) => request.destination === "image",
  new CacheFirst({
    cacheName: "linky-runtime-images-v1",
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 256,
        maxAgeSeconds: 60 * 60 * 24 * 30,
      }),
    ],
  }),
);

// Navigation route
registerRoute(
  new NavigationRoute(
    async () => {
      const cache = await caches.open("workbox-precache-v2");
      const response = await cache.match("/index.html");
      return response || fetch("/index.html");
    },
    {
      allowlist: [/^\/$/],
    },
  ),
);

// Push event handler
self.addEventListener("push", (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const contactNpub = data.data?.contactNpub;

    const options: NotificationOptions = {
      body: data.body || "New message",
      icon: "/pwa-192x192.png",
      badge: "/pwa-192x192.png",
      tag: contactNpub || "linky-message",
      requireInteraction: false,
      data: data.data || { type: "dm" },
    };

    // Update badge on app icon
    if ("setAppBadge" in navigator) {
      navigator.setAppBadge().catch(() => {
        // Ignore errors
      });
    }

    event.waitUntil(
      self.registration.showNotification(data.title || "Linky", options),
    );
  } catch {
    // Ignore errors
  }
});

// Notification click handler
self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  const data = event.notification.data;
  let url = "/";

  if (data?.type === "dm" && data?.contactNpub) {
    url = `/#/chat/${encodeURIComponent(data.contactNpub)}`;
  }

  // Clear badge
  if ("clearAppBadge" in navigator) {
    navigator.clearAppBadge().catch(() => {
      // Ignore errors
    });
  }

  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((clientList) => {
        for (const client of clientList) {
          if (client.url && "focus" in client) {
            return client.navigate(url).then(() => client.focus());
          }
        }
        if (self.clients.openWindow) {
          return self.clients.openWindow(url);
        }
      }),
  );
});

// Skip waiting and claim clients
self.addEventListener("install", () => {
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});
